In [15]:
from pathlib import Path
import pandas as pd
from IPython.display import display

In [16]:
DATASET_PATH = Path("../data/dataset_profesor.csv")
df = pd.read_csv(DATASET_PATH)

In [17]:
df.describe()

,tenure_months,monthly_spend,support_tickets_3m,usage_change_last_month,late_payments_6m,churn_next_month,cancellation_request_registered
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,36.708333,53.541667,1.458333,-0.011833,0.283333,0.200000,0.200000
std,19.820368,9.855661,1.505708,0.142133,0.552813,0.401677,0.401677
min,2.000000,30.700000,0.000000,-0.420000,0.000000,0.000000,0.000000
25%,20.000000,47.400000,0.000000,-0.090000,0.000000,0.000000,0.000000
50%,36.500000,53.050000,1.000000,0.010000,0.000000,0.000000,0.000000
75%,54.000000,60.750000,2.000000,0.080000,0.000000,0.000000,0.000000
max,71.000000,74.400000,9.000000,0.290000,2.000000,1.000000,1.000000

### `.T` traspone el dataframe

In [18]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
tenure_months,120.0,36.708333,19.820368,2.00,20.00,36.50,54.00,71.00
monthly_spend,120.0,53.541667,9.855661,30.70,47.40,53.05,60.75,74.40
support_tickets_3m,120.0,1.458333,1.505708,0.00,0.00,1.00,2.00,9.00
usage_change_last_month,120.0,-0.011833,0.142133,-0.42,-0.09,0.01,0.08,0.29
late_payments_6m,120.0,0.283333,0.552813,0.00,0.00,0.00,0.00,2.00
churn_next_month,120.0,0.200000,0.401677,0.00,0.00,0.00,0.00,1.00
cancellation_request_registered,120.0,0.200000,0.401677,0.00,0.00,0.00,0.00,1.00